# Workshop 0

In [54]:
#numpy import
import numpy as np
import time

In [3]:
#empty array eith size 2X2
empty_arr = np.empty((2, 2))
empty_arr

array([[6.23042070e-307, 4.67296746e-307],
       [1.69121096e-306, 2.33644129e-307]])

In [4]:
#one array eith size 4X2
ones_arr = np.ones((4, 2))
print(ones_arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [5]:
# Return a new array
full_arr = np.full((3, 3), 7)
print(full_arr)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [7]:
# New array of zeros
zeros_like_arr = np.zeros_like(ones_arr)
print(zeros_like_arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [8]:
# New array of ones with same
ones_like_arr = np.ones_like(empty_arr)
print(ones_like_arr)

[[1. 1.]
 [1. 1.]]


In [10]:
# Convert existing list to a numpy array
new_list = [1, 2, 3, 4]
converted_arr = np.array(new_list)
print(converted_arr)

[1 2 3 4]


# Array Manipulation


In [11]:
# Array with values ranging from 10 to 49
range_arr = np.arange(10, 50)
print(range_arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [12]:
# 3X3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print(matrix_3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [13]:
# 3X3 identity matrix
identity_3x3 = np.eye(3)
print(identity_3x3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
# Random array of size 30 and its mean
random_arr = np.random.random(30)
print(random_arr)

[0.6966844  0.35496173 0.88940276 0.31890762 0.57590364 0.37978009
 0.99605267 0.67710718 0.57790543 0.93524775 0.5734373  0.24413484
 0.57661394 0.11888853 0.266398   0.13750914 0.25593349 0.96183707
 0.32035362 0.96845427 0.52638175 0.42704362 0.55170662 0.09065005
 0.98704059 0.70616559 0.26046402 0.23497985 0.08069047 0.64103879]


In [15]:
mean_val = random_arr.mean()
print(mean_val)

0.5110558282731403


In [16]:
# 10X10 random array with min and max
large_random = np.random.random((10, 10))
print(large_random)

[[0.30707459 0.94034505 0.84473165 0.91864991 0.23114648 0.77306423
  0.39358183 0.21197853 0.23255721 0.42249927]
 [0.27807309 0.73208553 0.86523001 0.94079739 0.68963374 0.09341996
  0.98015282 0.61096992 0.87891825 0.63257489]
 [0.44001074 0.02296604 0.90409655 0.20970564 0.11697157 0.59693373
  0.20821822 0.57671914 0.48217754 0.69726753]
 [0.20948193 0.03324218 0.91788588 0.0420547  0.99968627 0.04787583
  0.62791803 0.64837327 0.44340219 0.31740702]
 [0.84097355 0.36101873 0.89029093 0.08371621 0.73252089 0.39783491
  0.23070083 0.20415421 0.56628001 0.15852618]
 [0.36532826 0.19346368 0.10994593 0.24445028 0.15384617 0.63369373
  0.0693638  0.09114272 0.51656278 0.70299883]
 [0.89738886 0.64747659 0.62236116 0.72689803 0.98056618 0.4606774
  0.11161951 0.63755908 0.24738273 0.70488284]
 [0.82312328 0.83122189 0.92084873 0.02065882 0.61347862 0.1352805
  0.64302474 0.96421979 0.72734363 0.29893531]
 [0.24706032 0.43491159 0.8572224  0.17878119 0.79285774 0.22820337
  0.62532187 0

In [17]:
min_val, max_val = large_random.min(), large_random.max()
print(min_val, max_val)

0.020658817346880354 0.9996862666393528


In [19]:
zero_vec = np.zeros(10)
print(zero_vec)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [20]:
zero_vec[4] = 1
print(zero_vec)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [21]:
arr_to_reverse = np.array([1, 2, 0, 0, 4, 0])
print(arr_to_reverse)

[1 2 0 0 4 0]


In [22]:
reversed_arr = arr_to_reverse[::-1]
print(reversed_arr)

[0 4 0 0 2 1]


In [23]:
border_arr = np.ones((5, 5))
print(border_arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [24]:
border_arr[1:-1, 1:-1] = 0
print(border_arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [26]:
# 8X8 matrix with checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
print(checkerboard)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [27]:
checkerboard[1::2, ::2] = 1
print(checkerboard)

[[0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]]


In [28]:
checkerboard[::2, 1::2] = 1
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# Array Operations

In [29]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

In [31]:
# Addition
add_res = np.add(x, y)
print(add_res)

[[ 6  8]
 [10 13]]


In [32]:
# Subtraction
sub_res = np.subtract(x, y)
print(sub_res)

[[-4 -4]
 [-4 -3]]


In [33]:
# Scalar multiplication
mult_res = x * 3
print(mult_res)

[[ 3  6]
 [ 9 15]]


In [34]:
# Square
square_res = np.square(x)
print(square_res)

[[ 1  4]
 [ 9 25]]


In [36]:
# Dot product
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)

In [39]:
# Concatenation
concat_row = np.concatenate((x, y), axis=0)
print(concat_row)

[[1 2]
 [3 5]
 [5 6]
 [7 8]]


In [40]:
concat_col_vw = np.column_stack((v, w))
print(concat_col_vw)

[[ 9 11]
 [10 12]]


In [42]:
try:
    bad_concat = np.concatenate((x, v))
except ValueError as e:
    print(f"Error explanation: {e}")

Error explanation: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


# Matrix Operations

In [43]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

In [45]:
inv_A = np.linalg.inv(A)
print(inv_A)

[[-2.    1.  ]
 [ 1.75 -0.75]]


In [47]:
proof1 = np.allclose(np.dot(A, inv_A), np.eye(2))
print(proof1)

True


In [49]:
# Prove AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)
proof2 = not np.array_equal(AB, BA)

print(proof2)

True


In [50]:
proof3 = np.allclose((np.dot(A, B)).T, np.dot(B.T, A.T))
print(proof3)

True


In [51]:
coeff_matrix = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
print(coeff_matrix)

[[ 2 -3  1]
 [ 1 -1  2]
 [ 3  1 -1]]


In [52]:
const_vector = np.array([-1, -3, 9])
print(const_vector)

[-1 -3  9]


In [53]:
solution = np.linalg.solve(coeff_matrix, const_vector)
print(solution)

[ 2.  1. -2.]


# How fast numpy is?

In [55]:
size = 1000000

In [56]:
list_a = list(range(size))
list_b = list(range(size))
array_a = np.arange(size)
array_b = np.arange(size)

In [64]:
start_time = time.time()
result_list = [list_a[i] + list_b[i] for i in range(size)]
python_add_time = time.time() - start_time
print(f"Python List Addition: {python_add_time:.5f} seconds")

Python List Addition: 0.22206 seconds


In [69]:
start_time = time.time()
result_array = array_a + array_b
numpy_add_time = time.time() - start_time
print(f"NumPy Array Addition: {numpy_add_time:.5f} seconds")

NumPy Array Addition: 0.00756 seconds


In [70]:
# Python List Multiplication
start_time = time.time()
result_list = [list_a[i] * list_b[i] for i in range(size)]
python_mul_time = time.time() - start_time
print(f"Python List Multiplication: {python_mul_time:.5f} seconds")

Python List Multiplication: 0.19254 seconds


In [71]:
# NumPy Array Multiplication
start_time = time.time()
result_array = array_a * array_b
numpy_mul_time = time.time() - start_time
print(f"NumPy Array Multiplication: {numpy_mul_time:.5f} seconds")

NumPy Array Multiplication: 0.00632 seconds


In [72]:
# Python List Dot Product
start_time = time.time()
dot_product_list = sum(list_a[i] * list_b[i] for i in range(size))
python_dot_time = time.time() - start_time
print(f"Python List Dot Product: {python_dot_time:.5f} seconds")

Python List Dot Product: 0.19004 seconds


In [73]:
# NumPy Array Dot Product
start_time = time.time()
dot_product_array = np.dot(array_a, array_b)
numpy_dot_time = time.time() - start_time
print(f"NumPy Array Dot Product: {numpy_dot_time:.5f} seconds")

NumPy Array Dot Product: 0.00000 seconds


In [74]:
matrix_size = 1000
mat_a = np.random.rand(matrix_size, matrix_size)
mat_b = np.random.rand(matrix_size, matrix_size)
list_mat_a = mat_a.tolist()
list_mat_b = mat_b.tolist()

# NumPy Matrix Multiplication
start_time = time.time()
result_numpy_mat = np.matmul(mat_a, mat_b)
numpy_mat_time = time.time() - start_time
print(f"NumPy Matrix Multiplication: {numpy_mat_time:.5f} seconds")


NumPy Matrix Multiplication: 0.03431 seconds
